---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: Vamsi
    name: postgres
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    author: Vamsi
    name: postgres
...