---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    author: Vamsi
    name: redis-pod
spec:
  containers:
    - name: reids
      image: redis
      ports:
        - containerPort: 6380
...