---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    author: Vamsi
    name: redis
spec:
  ports:
    - targetPort: 6380
      port: 6380
  selector:
    author: Vamsi
    name: redis-pod
...