---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    author: Vamsi
    name: result-app
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    author: Vamsi
    name: result-app
...