---
apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    author: Vamsi
    name: worker-app
spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
...